name: whisper_dart
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  ffi: ^2.1.0
  path: ^1.8.0

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^10.0.0
